### ISSUE TITLE
[BUG] Executor saved as string instead NULL (when duplicating prevent opening preset for instance)

### ISSUE THREAD

**Issue by Yivan** [elements-at/ExportToolkit#13]
Hello,

Using the "Duplicate" feature:

![image](https://user-images.githubusercontent.com/9025839/135520190-6eba4d1c-0199-418b-8226-59ee95456f1b.png)

Try duplicate the same one 2 or 3 times. When opening previous one this send a:

![image](https://user-images.githubusercontent.com/9025839/135520257-df2d42be-2c3d-4ab2-b68f-ca4ef288784b.png)

```
Timestamp: Thu Sep 30 2021 21:54:44 GMT+0200 (heure d’été d’Europe centrale)
Status: 500 | 
URL: /admin/elementsexporttoolkit/config/get
Message: Class "" not found
Trace: 
in /var/www/html/vendor/elements/export-toolkit-bundle/src/Controller/ConfigController.php:272
#0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Elements\Bundle\ExportToolkitBundle\Controller\ConfigController->getAction()
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(78): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle()
#3 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#4 {main}
```

And today I get the same message on a preset which was working fine before.

I digged in the code and it seems this is the executor which is saved as `"executor" => "",` in the `export-toolkit-configurations.php`. Replacing in this config by manually edit the php file by `"executor" => NULL,` make it works.

I think this field should be saved as NULL if empty in the GUI, or the line here https://github.com/elements-at/ExportToolkit/blob/master/src/Controller/ConfigController.php#L269 should check for empty too.

Thanks.

**Comment by Yivan** [comment]
I just saw there is already a PR fixing this: https://github.com/elements-at/ExportToolkit/pull/12
Please merge it and release a new version with this fix, it would be great.
Thanks.
